# Generated by Django 4.0.5 on 2022-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_document_summary_document_title'),
        ('exhibit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='items_in_exhibit',
            field=models.ManyToManyField(to='archive.document'),
        ),
    ]
